SELECT ROUTINE_NAME AS NAME
     , ROUTINE_TYPE AS TYPE
     , CREATED AS CREATED
     , LAST_ALTERED AS UPDATED
  FROM INFORMATION_SCHEMA.ROUTINES
 WHERE ROUTINE_NAME NOT LIKE 'sp_%'
   AND ROUTINE_NAME NOT LIKE 'fn_%'
